### ISSUE TITLE
Awesome and epic initiative from PalesaMn

### ISSUE THREAD

**Issue by PalesaMn** [ps-developers-sandbox/SARB-fundamentals#26]
### What happened?

Epic

- [x]  A feature from PalesaMn that rocks
- [x] Another epic feature from PalesaMn
- [x] Hot feature from PalesaMn

### Version

1.0.2 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
